[workspace]

members = [
    "statistics",
    "pig-latin-enc",
    "memanager",
    "cacher",
    "deref-enum-to-u8-slc",
    "data-structures",
    "gotmpl",
    "manfut",
    "slow-reader",
    "treiber-stack",
    "michael-scott-q",
    "harris-michael-list",
    "lazy-transform-lf",
]
